name: Smasfinland Robot Framework Browser Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  robot_test:
    runs-on: ubuntu-latest
    steps:
      - name: Robot Framework 
        uses: docker://marketsquare/robotframework-browser:latest
        with:
          run: robot -o NONE -l NONE -r NONE robot/SmashfinlandRobot
